sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.1
  - ruby-head
before_script:
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod 600 ~/.ssh/authorized_keys
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/id_rsa
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
notifications:
  email:
    - tj+travis_producer@a13.fr
